### Get nothing
GET {{host}}/api/v2/?method=beat
Accept: application/json

### Get example
GET {{host}}/api/v2/example
Accept: application/json

### Create custom read once paste
PUT {{host}}/api/v2/example
Content-Type: application/json
Accept: application/json

{
  "lang": "plain",
  "content": "Hello World!"
}

### Create permanent
POST {{host}}/api/v2
Content-Type: application/json
Accept: application/json

{
  "lang": "plain",
  "content": "Hello World!"
}

### Get example
GET {{host}}/api/v2/100?json
Accept: application/json

### Get nothing
GET {{host}}/api/v3/?method=beat
Accept: application/json

### Get paste
GET {{host}}/api/v3/lucienshui/100
Accept: application/json
